theme: jekyll-theme-cayman
url: https://thorleifurb.github.io
baseurl: /
github:
  is_project_page: true
  is_user_page: true
  linkedin: https://www.linkedin.com/in/thorleifur/
  bio: Over 30 years of software development and project management.\r\nExpert in Integration. Experienced user of Software AG's webMethods and Azure Integration
